site_name: fiware-sinfonier
site_description: Sinfonier Documentation
docs_dir: docs/manuals/
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - 'Home': 'index.md'
  - 'User and Programmer manual':
      - 'Introduction': 'user_and_programmer_manual/introduction.md'
      - 'Apche Storm & Sinfonier': 'user_and_programmer_manual/streaming/stream_processing_storm_sinfonier.md'
      - 'Sinfonier Topologies': 'user_and_programmer_manual/streaming/stream_processing_sinfonier_topologies.md'
      - 'Sinfonier Modules': 'user_and_programmer_manual/streaming/stream_processing_sinfonier_modules.md'